project:
  type: website

website:
  title: "Christophe BOGHOSSIAN"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: research.qmd
        text: Recherche & Stages
      - href: cv.qmd
        text: CV / Parcours

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex